from __future__ import annotations

import csv
import html
import math
import os
import re
import shutil
import xml.etree.ElementTree as ET
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

from dmm.config.constants import (
    RMU_LABEL_EDGE_TOLERANCE,
    RMU_LABEL_PATTERN,
    RMU_LABEL_SEARCH_MAX_DISTANCE,
)
from dmm.config.defaults import DEFAULT_RMU_NAME_EXCLUSIONS
from dmm.domain.gfile.parser import GObject, GParser, ParsedG, RmuFrame


# Makkah annotation layout rules.
#
# * RMU cabinet names are anchored at the midpoint of one of the four frame
#   edges (top/right/bottom/left).
# * NOP is NOT centered to the RMU frame.  It belongs to an in-cabinet Y*/Q*
#   switch (Y1/Y2/Y3/Q1/Q2/Q3...) and must be horizontally center-aligned with
#   that switch, i.e. NOP.center_y == switch.center_y.  NOP therefore lives on
#   the left or right side of the cabinet only.
RMU_NAME_POSITIONS: dict[str, str] = {
    "top": "上边中点",
    "right": "右边中点",
    "bottom": "下边中点",
    "left": "左边中点",
}

NOP_HORIZONTAL_POSITIONS: dict[str, str] = {
    "auto": "自动保持原左右侧",
    "left": "左侧（与开关水平中心对齐）",
    "right": "右侧（与开关水平中心对齐）",
}

# Backward-compatible alias for earlier internal callers/tests.
EDGE_CENTER_POSITIONS = RMU_NAME_POSITIONS

NOP_RMU_SEARCH_DISTANCE = 330.0

_PATH_COORD_PATTERN = re.compile(r"(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)")
_X_POSITION_ATTRS = ("x", "x1", "x2", "cx", "mergex")
_Y_POSITION_ATTRS = ("y", "y1", "y2", "cy", "mergey")

# Poke objects generated by G File Studio / DMM carry one of these Text-ID
# metadata fields.  Older field drawings may contain a plain <poke> without
# metadata, so a strict geometry fallback is also used below.
_POKE_TEXT_ID_ATTRS = (
    "dmm_source_text_id",
    "dmm_rmu_text_id",
    "gfs_rmu_text_id",
)


def _local_name(tag) -> str:
    return str(tag or "").rsplit("}", 1)[-1]


def _element_box(element: ET.Element):
    try:
        x = float(element.get("x", "0"))
        y = float(element.get("y", "0"))
        w = float(element.get("w", element.get("width", "0")))
        h = float(element.get("h", element.get("height", "0")))
    except (TypeError, ValueError):
        return None
    if w <= 0 or h <= 0:
        return None
    return x, y, w, h


def _box_overlap_ratio(a, b) -> float:
    ax, ay, aw, ah = a
    bx, by, bw, bh = b
    ix = max(0.0, min(ax + aw, bx + bw) - max(ax, bx))
    iy = max(0.0, min(ay + ah, by + bh) - max(ay, by))
    intersection = ix * iy
    base = min(max(aw * ah, 1e-9), max(bw * bh, 1e-9))
    return intersection / base


def _related_name_pokes(parsed: ParsedG, name: GObject) -> list[ET.Element]:
    """Return Poke click-regions owned by one RMU name Text.

    Prefer explicit Text-ID metadata written by G File Studio/DMM.  For older
    drawings without metadata, accept only an ahref-bearing Poke whose click box
    substantially overlaps the RMU-name Text box.  This avoids moving unrelated
    Pokes merely because they are nearby.
    """
    text_id = str(name.xml_id or "").strip()
    name_box = (float(name.box.x), float(name.box.y), float(name.box.w), float(name.box.h))
    explicit: list[ET.Element] = []
    geometric: list[ET.Element] = []
    for element in parsed.layer.iter():
        if _local_name(element.tag).lower() != "poke":
            continue
        if text_id and any(str(element.get(attr) or "").strip() == text_id for attr in _POKE_TEXT_ID_ATTRS):
            explicit.append(element)
            continue
        if not str(element.get("ahref") or "").strip():
            continue
        poke_box = _element_box(element)
        if poke_box is None:
            continue
        if _box_overlap_ratio(name_box, poke_box) >= 0.80:
            geometric.append(element)
    # Explicit ownership is authoritative.  Geometry fallback is used only when
    # no metadata-linked Poke exists for this Text.
    return explicit if explicit else geometric


@dataclass
class RmuAnnotationPositionFileRecord:
    file_name: str
    rmu_count: int = 0
    rmu_name_found: int = 0
    rmu_name_moved: int = 0
    rmu_name_missing: int = 0
    rmu_name_poke_found: int = 0
    rmu_name_poke_moved: int = 0
    nop_found: int = 0
    nop_moved: int = 0
    nop_unmatched_rmu: int = 0
    nop_unmatched_device: int = 0
    nop_position: str = "auto"
    rmu_name_position: str = "right"
    nop_margin: int = 5
    rmu_name_margin: int = 5
    status: str = "NO_MATCH"


@dataclass
class RmuAnnotationPositionResult:
    output_files: list[Path]
    records: list[RmuAnnotationPositionFileRecord]
    csv_path: Path
    html_path: Path
    rmu_name_found: int
    rmu_name_moved: int
    rmu_name_missing: int
    rmu_name_poke_found: int
    rmu_name_poke_moved: int
    nop_found: int
    nop_moved: int
    nop_unmatched_rmu: int
    nop_unmatched_device: int


def _format_number(value: float) -> str:
    if not math.isfinite(value):
        raise ValueError(f"非有限数值：{value}")
    rounded = round(value)
    if abs(value - rounded) < 1e-9:
        return str(int(rounded))
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return "0" if text in {"-0", "-0.0"} else text


def _translate_number(value: str, delta: float) -> str:
    try:
        return _format_number(float(value) + delta)
    except (TypeError, ValueError):
        return value


def _translate_path_xy(value: str, delta_x: float, delta_y: float) -> str:
    return _PATH_COORD_PATTERN.sub(
        lambda match: (
            f"{_translate_number(match.group(1), delta_x)},"
            f"{_translate_number(match.group(2), delta_y)}"
        ),
        value,
    )


def _translate_element_xy(element: ET.Element, delta_x: float, delta_y: float) -> bool:
    if abs(delta_x) <= 1e-9 and abs(delta_y) <= 1e-9:
        return False
    changed = False
    for node in element.iter():
        for attr in _X_POSITION_ATTRS:
            if attr in node.attrib:
                old = node.get(attr, "")
                new = _translate_number(old, delta_x)
                if new != old:
                    node.set(attr, new)
                    changed = True
        for attr in _Y_POSITION_ATTRS:
            if attr in node.attrib:
                old = node.get(attr, "")
                new = _translate_number(old, delta_y)
                if new != old:
                    node.set(attr, new)
                    changed = True
        if "d" in node.attrib:
            old = node.get("d", "")
            new = _translate_path_xy(old, delta_x, delta_y)
            if new != old:
                node.set("d", new)
                changed = True
    return changed


def _write_tree_atomic(root: ET.Element, output_path: Path) -> None:
    output_path = Path(output_path)
    temp = output_path.with_name(output_path.name + ".tmp_rmu_annotation_position")
    ET.ElementTree(root).write(temp, encoding="utf-8", xml_declaration=True)
    ET.parse(temp)
    os.replace(temp, output_path)


def _is_nop_text(obj: GObject) -> bool:
    if obj.tag.lower() != "text":
        return False
    value = str(obj.attrs.get("ts") or "").strip().upper()
    return re.sub(r"[\s._-]+", "", value) == "NOP"


def _frame_key(frame: RmuFrame) -> tuple[int, str]:
    return frame.frame.xml_index, frame.frame.xml_id


def _element_map(parsed: ParsedG) -> dict[int, ET.Element]:
    # GParser assigns xml_index from enumerate(layer.iter()) while skipping the
    # layer itself. Rebuild the same mapping on the exact parsed XML tree.
    return {
        idx: element
        for idx, element in enumerate(parsed.layer.iter())
        if element is not parsed.layer
    }


def _new_makkah_parser() -> GParser:
    return GParser(
        required_rmu_tags={"CBreakerDis", "ZhaiWaiJieDiDaoZha", "BusDis"},
        label_regex=RMU_LABEL_PATTERN,
        max_distance=RMU_LABEL_SEARCH_MAX_DISTANCE,
        overlap_tolerance=RMU_LABEL_EDGE_TOLERANCE,
        excluded_rmu_name_strings=DEFAULT_RMU_NAME_EXCLUSIONS,
        exclude_numeric_decimal_rmu_names=True,
        exclude_phone_like_rmu_names=True,
        exclude_hyphenated_rmu_names=True,
        prefer_pure_numeric_rmu_names=False,
    )


def _objects_inside_frame(parsed: ParsedG, frame: RmuFrame) -> list[GObject]:
    return [
        obj
        for obj in parsed.objects
        if obj is not frame.frame
        and frame.frame.box.center_contains(obj.box, tolerance=1.0)
    ]


def _assign_nops_to_frames(
    parsed: ParsedG,
    frames: list[RmuFrame],
) -> tuple[list[tuple[GObject, RmuFrame]], list[GObject]]:
    """Assign each NOP Text to the nearest RMU frame once.

    The 330-unit cap mirrors the existing feeder-ownership NOP search radius.
    Global nearest assignment prevents one NOP Text from being consumed by two
    neighbouring cabinets.
    """
    pairs: list[tuple[float, int, int, GObject, RmuFrame]] = []
    nops = [obj for obj in parsed.objects if _is_nop_text(obj)]
    for nop in nops:
        for frame in frames:
            distance = nop.box.edge_distance(frame.frame.box)
            if distance <= NOP_RMU_SEARCH_DISTANCE:
                pairs.append((
                    float(distance),
                    int(nop.xml_index),
                    int(frame.frame.xml_index),
                    nop,
                    frame,
                ))
    pairs.sort(key=lambda item: (item[0], item[1], item[2]))
    used_nops: set[int] = set()
    assignments: list[tuple[GObject, RmuFrame]] = []
    for _distance, _nop_order, _frame_order, nop, frame in pairs:
        if nop.xml_index in used_nops:
            continue
        used_nops.add(nop.xml_index)
        assignments.append((nop, frame))
    unmatched = [nop for nop in nops if nop.xml_index not in used_nops]
    return assignments, unmatched


def _named_yq_switches(
    parser: GParser,
    parsed: ParsedG,
    frame: RmuFrame,
) -> list[tuple[GObject, str]]:
    """Return in-frame CBreakerDis devices whose logical name is Y* or Q*.

    ``p_NameString`` is authoritative when it already contains Y1/Q1-style
    engineering names.  Visible graphical text is used only as the same
    fallback already used by the Makkah RMU validator.  This deliberately
    excludes unrelated disconnectors/grounds so NOP can never align to a
    random symbol merely because it is geometrically close.
    """
    breakers = [
        obj
        for obj in _objects_inside_frame(parsed, frame)
        if obj.tag == "CBreakerDis"
    ]
    if not breakers:
        return []

    try:
        graphical = parser.resolve_breaker_graphical_names(parsed, frame, breakers)
    except Exception:
        graphical = {}

    result: list[tuple[GObject, str]] = []
    for device in breakers:
        logical_name = str(device.xml_p_name_string or "").strip().upper()
        if not re.fullmatch(r"[YQ]\d+", logical_name):
            info = graphical.get(device.xml_id, {}) if graphical else {}
            visible = (
                str(info.get("name") or "").strip().upper()
                if info.get("status") == "PASS"
                else ""
            )
            logical_name = visible
        if re.fullmatch(r"[YQ]\d+", logical_name):
            result.append((device, logical_name))

    def _name_key(item):
        device, name = item
        prefix = 0 if name.startswith("Y") else 1
        try:
            number = int(name[1:])
        except ValueError:
            number = 10**9
        return prefix, number, device.xml_index

    return sorted(result, key=_name_key)


def _corresponding_nop_device(
    parser: GParser,
    parsed: ParsedG,
    frame: RmuFrame,
    nop: GObject,
    preferred_side: str = "auto",
) -> tuple[GObject, str] | None:
    """Resolve the Y*/Q* switch whose row the NOP belongs to.

    The NOP's display side also carries useful field-layout evidence.  A NOP
    shown on the right should first consider Y*/Q* switches on the right half
    of the cabinet (and likewise for the left), then choose the closest switch
    row by center-Y distance.  This prevents a right-side NOP from jumping to a
    left-side Y/Q device merely because the two rows happen to be close.
    """
    fb = frame.frame.box
    side = preferred_side
    if side == "auto":
        side = "left" if nop.box.cx < fb.cx else "right"

    candidates = []
    for device, logical_name in _named_yq_switches(parser, parsed, frame):
        device_side = "left" if device.box.cx < fb.cx else "right"
        side_penalty = 0 if device_side == side else 1
        candidates.append((
            side_penalty,
            abs(float(nop.box.cy) - float(device.box.cy)),
            float(nop.box.edge_distance(device.box)),
            abs(float(nop.box.cx) - float(device.box.cx)),
            int(device.xml_index),
            device,
            logical_name,
        ))
    if not candidates:
        return None
    candidates.sort(key=lambda item: item[:5])
    return candidates[0][5], candidates[0][6]


def _target_for_rmu_name(frame: RmuFrame, name: GObject, side: str, margin: float) -> tuple[float, float]:
    fb = frame.frame.box
    nb = name.box
    if side == "top":
        return fb.cx - nb.w / 2.0, fb.top - margin - nb.h
    if side == "bottom":
        return fb.cx - nb.w / 2.0, fb.bottom + margin
    if side == "left":
        return fb.left - margin - nb.w, fb.cy - nb.h / 2.0
    if side == "right":
        return fb.right + margin, fb.cy - nb.h / 2.0
    raise ValueError(f"不支持的环网柜名称位置：{side!r}")


def _target_for_nop(
    frame: RmuFrame,
    device: GObject,
    nop: GObject,
    side: str,
    margin: float,
) -> tuple[float, float, str]:
    """Place NOP left/right of the RMU and center-align it with its Y*/Q* switch.

    Horizontal alignment means both centers share the same Y coordinate.  The
    X coordinate only decides which cabinet side the NOP is displayed on.
    ``auto`` preserves the NOP's existing left/right side whenever possible.
    """
    fb = frame.frame.box
    db = device.box
    nb = nop.box
    resolved_side = side
    if side == "auto":
        resolved_side = "left" if nb.cx < fb.cx else "right"
    if resolved_side == "left":
        target_x = fb.left - margin - nb.w
    elif resolved_side == "right":
        target_x = fb.right + margin
    else:
        raise ValueError(f"不支持的 NOP 位置：{side!r}")
    target_y = db.cy - nb.h / 2.0
    return target_x, target_y, resolved_side


def reposition_rmu_annotations(
    parsed: ParsedG,
    *,
    nop_position: str = "auto",
    rmu_name_position: str = "right",
    nop_margin: float = 5.0,
    rmu_name_margin: float = 5.0,
) -> dict[str, int]:
    if nop_position not in NOP_HORIZONTAL_POSITIONS:
        raise ValueError(f"不支持的 NOP 位置：{nop_position!r}")
    if rmu_name_position not in RMU_NAME_POSITIONS:
        raise ValueError(f"不支持的环网柜名称位置：{rmu_name_position!r}")
    if float(nop_margin) < 0 or float(rmu_name_margin) < 0:
        raise ValueError("距边像素不能小于 0。")

    parser = _new_makkah_parser()
    # The parser methods use only ParsedG data, so keep the already parsed tree
    # instead of re-reading the file and risking a different element mapping.
    frames = parser.find_rmu_frames(parsed)
    elements = _element_map(parsed)

    # Makkah RMU-name ownership is RIGHT -> BOTTOM -> GLOBAL fallback.
    assigned_names = parser.assign_rmu_label_candidates_globally(
        parsed,
        frames,
        ("right", "bottom", "global"),
    )

    name_found = 0
    name_moved = 0
    name_missing = 0
    rmu_name_poke_found = 0
    rmu_name_poke_moved = 0
    moved_poke_objects: set[int] = set()
    for frame in frames:
        candidates = assigned_names.get(_frame_key(frame), [])
        if not candidates:
            name_missing += 1
            continue
        name = candidates[0].obj
        element = elements.get(name.xml_index)
        if element is None:
            name_missing += 1
            continue
        name_found += 1
        target_x, target_y = _target_for_rmu_name(
            frame,
            name,
            rmu_name_position,
            float(rmu_name_margin),
        )
        delta_x = target_x - name.box.x
        delta_y = target_y - name.box.y
        related_pokes = _related_name_pokes(parsed, name)
        rmu_name_poke_found += len(related_pokes)
        if _translate_element_xy(element, delta_x, delta_y):
            name_moved += 1
            # A Poke is an invisible click region linked to the name Text.  It
            # must receive the exact same translation, otherwise the visible
            # label and its clickable jump target become separated.
            for poke in related_pokes:
                poke_key = id(poke)
                if poke_key in moved_poke_objects:
                    continue
                if _translate_element_xy(poke, delta_x, delta_y):
                    rmu_name_poke_moved += 1
                moved_poke_objects.add(poke_key)

    nop_assignments, unmatched_nops = _assign_nops_to_frames(parsed, frames)
    nop_found = len(nop_assignments) + len(unmatched_nops)
    nop_moved = 0
    nop_unmatched_device = 0
    for nop, frame in nop_assignments:
        resolved = _corresponding_nop_device(
            parser, parsed, frame, nop, preferred_side=nop_position
        )
        if resolved is None:
            nop_unmatched_device += 1
            continue
        device, device_name = resolved
        element = elements.get(nop.xml_index)
        if element is None:
            nop_unmatched_device += 1
            continue
        target_x, target_y, resolved_side = _target_for_nop(
            frame,
            device,
            nop,
            nop_position,
            float(nop_margin),
        )
        if _translate_element_xy(element, target_x - nop.box.x, target_y - nop.box.y):
            nop_moved += 1

    return {
        "rmu_count": len(frames),
        "rmu_name_found": name_found,
        "rmu_name_moved": name_moved,
        "rmu_name_missing": name_missing,
        "rmu_name_poke_found": rmu_name_poke_found,
        "rmu_name_poke_moved": rmu_name_poke_moved,
        "nop_found": nop_found,
        "nop_moved": nop_moved,
        "nop_unmatched_rmu": len(unmatched_nops),
        "nop_unmatched_device": nop_unmatched_device,
    }


def _write_csv(records: list[RmuAnnotationPositionFileRecord], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = list(RmuAnnotationPositionFileRecord.__dataclass_fields__)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for record in records:
            writer.writerow(asdict(record))
    return path


def _write_html(records: list[RmuAnnotationPositionFileRecord], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for record in records:
        row_class = "pass" if (record.rmu_name_moved or record.nop_moved) else "info"
        rows.append(
            "<tr class='%s'><td>%s</td><td>%d</td><td>%d/%d/%d</td><td>%d/%d</td><td>%d/%d/%d/%d</td><td>%s</td><td>%s</td><td>%d</td><td>%d</td><td>%s</td></tr>"
            % (
                row_class,
                html.escape(record.file_name),
                record.rmu_count,
                record.rmu_name_found,
                record.rmu_name_moved,
                record.rmu_name_missing,
                record.rmu_name_poke_found,
                record.rmu_name_poke_moved,
                record.nop_found,
                record.nop_moved,
                record.nop_unmatched_rmu,
                record.nop_unmatched_device,
                html.escape(NOP_HORIZONTAL_POSITIONS.get(record.nop_position, record.nop_position)),
                html.escape(RMU_NAME_POSITIONS.get(record.rmu_name_position, record.rmu_name_position)),
                record.nop_margin,
                record.rmu_name_margin,
                html.escape(record.status),
            )
        )
    content = f"""<!doctype html>
<html lang='zh-CN'><head><meta charset='utf-8'><title>NOP / 环网柜名称位置调整报告</title>
<style>
body{{font-family:'Microsoft YaHei','Segoe UI',Arial,sans-serif;margin:24px;background:#f3f7f5;color:#17372e}}
h1{{color:#006b52}} .rule{{background:#eaf8f2;border:1px solid #b8dfd1;padding:12px 14px;margin-bottom:16px;border-radius:8px;line-height:1.7}}
table{{border-collapse:collapse;width:100%;background:white;font-size:12px}}th,td{{border:1px solid #d3e3dc;padding:7px 9px;text-align:left;white-space:nowrap}}th{{background:#006b52;color:white}}.pass{{background:#eaf8f2}}.info{{background:#eaf3ff}}
</style></head><body><h1>NOP / 环网柜名称位置调整报告</h1>
<div class='rule'>NOP：先匹配最近 RMU，再只在柜内 Y*/Q* CBreakerDis（如 Y1/Y2/Y3/Q1/Q2/Q3）中匹配对应开关；NOP 仅放在柜体左/右侧，且 NOP 中心 Y 与该开关中心 Y 完全一致。环网柜名称识别：名称 Text 中心必须在所有 RMU 框外，之后按 RIGHT → BOTTOM → GLOBAL fallback 一柜一名称；位置仍可放到 RMU 外框上/右/下/左四边中点。若名称 Text 已有 Poke 跳转，移动名称时 Poke 使用相同位移同步移动。原始 G 文件不修改，只写 Workspace 安全副本。</div>
<table><thead><tr><th>G文件</th><th>有效RMU</th><th>名称 找到/移动/缺失</th><th>名称Poke 找到/移动</th><th>NOP 找到/移动/无RMU/无设备</th><th>NOP位置</th><th>名称位置</th><th>NOP距边</th><th>名称距边</th><th>状态</th></tr></thead><tbody>{''.join(rows)}</tbody></table></body></html>"""
    path.write_text(content, encoding="utf-8")
    return path


def process_rmu_annotation_reposition(
    files: Iterable[Path],
    output_dir: Path,
    report_dir: Path,
    *,
    nop_position: str = "auto",
    rmu_name_position: str = "right",
    nop_margin: int = 5,
    rmu_name_margin: int = 5,
    log=None,
    progress=None,
) -> RmuAnnotationPositionResult:
    if nop_position not in NOP_HORIZONTAL_POSITIONS:
        raise ValueError(f"不支持的 NOP 位置：{nop_position!r}")
    if rmu_name_position not in RMU_NAME_POSITIONS:
        raise ValueError(f"不支持的环网柜名称位置：{rmu_name_position!r}")
    if int(nop_margin) < 0 or int(rmu_name_margin) < 0:
        raise ValueError("距边像素不能小于 0。")

    log = log or (lambda _message: None)
    files = [Path(path) for path in files]
    if not files:
        raise ValueError("没有可处理的 G 文件。")

    output_dir = Path(output_dir)
    report_dir = Path(report_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)

    output_files: list[Path] = []
    records: list[RmuAnnotationPositionFileRecord] = []
    totals = {
        "rmu_name_found": 0,
        "rmu_name_moved": 0,
        "rmu_name_missing": 0,
        "rmu_name_poke_found": 0,
        "rmu_name_poke_moved": 0,
        "nop_found": 0,
        "nop_moved": 0,
        "nop_unmatched_rmu": 0,
        "nop_unmatched_device": 0,
    }

    parser = _new_makkah_parser()
    for index, source in enumerate(files, start=1):
        if progress:
            progress(
                int((index - 1) / max(1, len(files)) * 95),
                f"正在调整 NOP / 环网柜名称：{source.name}",
            )
        target = output_dir / source.name
        shutil.copy2(source, target)
        log(f"[安全副本] {source} -> {target}")

        parsed = parser.parse(target)
        counts = reposition_rmu_annotations(
            parsed,
            nop_position=nop_position,
            rmu_name_position=rmu_name_position,
            nop_margin=float(nop_margin),
            rmu_name_margin=float(rmu_name_margin),
        )
        _write_tree_atomic(parsed.root, target)

        for key in totals:
            totals[key] += int(counts[key])
        moved_total = int(counts["rmu_name_moved"]) + int(counts["nop_moved"])
        found_total = int(counts["rmu_name_found"]) + int(counts["nop_found"])
        status = "MOVED" if moved_total else ("ALREADY_AT_TARGET" if found_total else "NO_MATCH")
        record = RmuAnnotationPositionFileRecord(
            file_name=target.name,
            rmu_count=int(counts["rmu_count"]),
            rmu_name_found=int(counts["rmu_name_found"]),
            rmu_name_moved=int(counts["rmu_name_moved"]),
            rmu_name_missing=int(counts["rmu_name_missing"]),
            rmu_name_poke_found=int(counts["rmu_name_poke_found"]),
            rmu_name_poke_moved=int(counts["rmu_name_poke_moved"]),
            nop_found=int(counts["nop_found"]),
            nop_moved=int(counts["nop_moved"]),
            nop_unmatched_rmu=int(counts["nop_unmatched_rmu"]),
            nop_unmatched_device=int(counts["nop_unmatched_device"]),
            nop_position=nop_position,
            rmu_name_position=rmu_name_position,
            nop_margin=int(nop_margin),
            rmu_name_margin=int(rmu_name_margin),
            status=status,
        )
        records.append(record)
        output_files.append(target)
        log(
            f"[NOP/名称位置] {target.name}: 有效RMU={record.rmu_count}, "
            f"名称找到={record.rmu_name_found}, 名称移动={record.rmu_name_moved}, "
            f"名称Poke找到={record.rmu_name_poke_found}, 名称Poke移动={record.rmu_name_poke_moved}, "
            f"NOP找到={record.nop_found}, NOP移动={record.nop_moved}, "
            f"NOP无RMU={record.nop_unmatched_rmu}, NOP无柜内设备={record.nop_unmatched_device}, "
            f"NOP位置={NOP_HORIZONTAL_POSITIONS[nop_position]}, "
            f"名称位置={RMU_NAME_POSITIONS[rmu_name_position]}"
        )

    csv_path = _write_csv(records, report_dir / "rmu_annotation_position_report.csv")
    html_path = _write_html(records, report_dir / "rmu_annotation_position_report.html")
    if progress:
        progress(100, "NOP / 环网柜名称位置调整完成")
    return RmuAnnotationPositionResult(
        output_files=output_files,
        records=records,
        csv_path=csv_path,
        html_path=html_path,
        **totals,
    )
